class_path: chebai.loggers.custom.CustomLogger # Extension of Wandb logger
init_args:
  save_dir: /Users/ctumes/Cheb-AI/bbbp/runs_no_onto/
  project: 'chebai-bbbp'
  entity: 'ch-tumescheit-university-of-zurich'
  log_model: 'all'
