class_path: chebai.loggers.custom.CustomLogger # Extension of Wandb logger
init_args:
  save_dir: /Users/ctumes/Cheb-AI/runs_no_onto/
  # version: no-onto
  project: 'cheb-ai-sol'
  entity: 'ch-tumescheit-university-of-zurich'
  log_model: 'all'
